### ISSUE TITLE
panic: core init set time zone fail.

### ISSUE THREAD

**Issue by bishamonzy** [Higker/logker#3]
goroutine 1 [running]:
github.com/higker/logker.(*timeZone).localTime(0xc000092080, 0x502eb8, 0xa33de0, 0xb62e20)
        D:/GoWroks/pkg/mod/github.com/higker/logker@v1.2.2/time.go:71 +0x128
github.com/higker/logker.(*timeZone).NowTimeStr(0xc000092080, 0x80, 0xc0000c0080)
        D:/GoWroks/pkg/mod/github.com/higker/logker@v1.2.2/time.go:53 +0x32
github.com/higker/logker.(*fileLog).pack(0xc00009a080, 0x3, 0xc0000c0080, 0x7c, 0x1)
        D:/GoWroks/pkg/mod/github.com/higker/logker@v1.2.2/message.go:25 +0x3a
github.com/higker/logker.(*fileLog).Error(0xc00009a080, 0xb8f9f5, 0x19, 0xc000092090, 0x1, 0x1)
        D:/GoWroks/pkg/mod/github.com/higker/logker@v1.2.2/file.go:122 +0x9e

**Comment by bishamonzy** [comment]
LoadLocation 有个问题，它依赖于 IANA Time Zone Database (简称 tzdata 吧) 这个数据库，一般linux系统都带了，但是windows系统就没带。
没有 zoneinfo 就会从$GOROOT/中找。对于没有安装go环境的windows系统来说，就没办法通过 LoadLocation 设置时区。
但是也有办法，我们可以自己把zoneinfo.zip文件放到自己的程序目录中，然后让 time 包能够从我们自己的程序目录中加载时区文件就可以了。
文件目录可以通过环境变量设置，在main方法中:
os.Setenv("ZONEINFO", '/home/tz/zoneinfo.zip')
然后再调用 LoadLocation 方法就可以了。

**Comment by auula** [comment]
> LoadLocation有个问题，它依赖于IANA时区数据库（简称tzdata吧）这个数据库，一般linux系统都带了，但是windows系统就没带。
> 没有zoneinfo就会从$ GOROOT /中找。对于没有安装go环境的窗口系统而言，就没办法通过LoadLocation设置时区。
> 但是也有办法，我们可以自己把zoneinfo.zip文件放到自己的程序目录中，然后让时间包能够从我们自己的程序目录中加载时区文件就可以了。
> 文件目录可以通过环境变量设置，在主要方法中：
> os.Setenv（“ ZONEINFO”，'/home/tz/zoneinfo.zip'）
> 然后再调用LoadLocation方法就可以了。

谢谢这个问题，我有空的时候研究一下，谢谢你，我会在后面的更新版本中进行修复~
