### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by Heyra-Joker** [Higker/logker#8]
undefined: errPerfix

![image](https://user-images.githubusercontent.com/30002208/108798953-f8eba080-75c9-11eb-81c1-61733fba3039.png)

**Comment by higker** [comment]
这版本已经废弃，这个库是我写golang半个月的时候写的，现在打算全部重构一下的，等我有空我重构一下的。

**Comment by auula** [comment]
> undefined: errPerfix
> 
> ![image](https://user-images.githubusercontent.com/30002208/108798953-f8eba080-75c9-11eb-81c1-61733fba3039.png)

这版本已经废弃，这个库是我学golang半个月的时候写的，现在打算全部重构一下的，等我有空我重构一下的。
